[platformio]
description = Firmware LoRaWAN basse consommation pour Mji_Safi_Connect

[env:heltec_wifi_lora_32_v3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
lib_deps =
    heltecautomation/Heltec ESP32 Dev-Boards @ ^2.1.1
build_flags =
    -D REGION_EU868
